#!/usr/bin/env bash
# PTC仿真系统 - 快速启动脚本

echo "════════════════════════════════════════════════════"
echo "  PTC 自恢复保险丝仿真系统 v1.0"
echo "════════════════════════════════════════════════════"
echo ""
echo "📦 已创建的文件："
echo "  ✓ ptc-fuse-demo.html           - 基础演示版本"
echo "  ✓ ptc-complete-demo.html       - 完整版本（推荐）"
echo "  ✓ ptc-fuse-simulator.js        - 仿真引擎模块"
echo "  ✓ ptc-quick-reference.html     - 快速参考卡（可打印）"
echo "  ✓ index-ptc.html               - 项目中心"
echo "  ✓ README.md                    - 项目总结"
echo "  ✓ PTC_GUIDE.md                 - 完整技术指南"
echo ""
echo "🚀 快速开始："
echo "  1. 在浏览器中打开以下任一文件："
echo "     • ptc-fuse-demo.html        （推荐新手）"
echo "     • ptc-complete-demo.html    （推荐深入学习）"
echo "     • index-ptc.html            （项目导航）"
echo ""
echo "  2. 或启动本地HTTP服务器："
echo "     python -m http.server 8000"
echo "     然后访问 http://localhost:8000/index-ptc.html"
echo ""
echo "📚 学习路径："
echo "  阶段1：打开ptc-fuse-demo.html → 观看演示"
echo "  阶段2：打开ptc-complete-demo.html → 深入学习"
echo "  阶段3：阅读PTC_GUIDE.md → 理解原理"
echo "  阶段4：查看ptc-quick-reference.html → 快速查询"
echo ""
echo "💡 核心概念："
echo "  • 正常工作：PTC电阻小(10Ω) → 电流大(1A)"
echo "  • 过流保护：焦耳热 → 温度升高 → 电阻大(1MΩ) → 电流小"
echo "  • 自动恢复：故障消除 → 温度降低 → 电阻恢复 → 重复使用"
echo ""
echo "📊 仿真特点："
echo "  ✓ 完整物理模型（分段非线性R-T特性）"
echo "  ✓ 热动力学精确计算"
echo "  ✓ 实时参数可调"
echo "  ✓ 四路波形显示"
echo "  ✓ 对数刻度电阻"
echo "  ✓ 故障场景模拟"
echo ""
echo "🔧 仿真引擎导入："
echo "  import { PTCResettableFuseSimulator } from './ptc-fuse-simulator.js';"
echo "  const ptc = new PTCResettableFuseSimulator({"
echo "      Vsupply: 12,    // 供电电压"
echo "      Rload: 5,       // 负载电阻"
echo "      Tswitch: 80,    // 切换温度"
echo "      Tcurie: 110     // 居里温度"
echo "  });"
echo "  ptc.update(0.01);   // 运行仿真"
echo ""
echo "📱 应用场景："
echo "  • USB充电保护（5V/2.5A）"
echo "  • 电池管理系统（12～48V）"
echo "  • 通讯基站电源（48V/6A）"
echo "  • 工业控制（380V/30～50A）"
echo ""
echo "❓ 遇到问题？"
echo "  查看 PTC_GUIDE.md 的"常见问题"部分"
echo ""
echo "════════════════════════════════════════════════════"
echo "版本：1.0 | 日期：2026年5月 | 教学使用"
echo "════════════════════════════════════════════════════"
